name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        api-level: [21]  # Add the Android API levels you want to test
        target: [google_apis]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: 8512546
   
    - name: Installed Packages
      run: sdkmanager --install "platform-tools" "system-images;android-29;google_apis;x86_64" "emulator"
    - name: Enable KVM
      run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
    - name: Start Emulator
      run: |
    
        echo "no" | avdmanager create avd --force --name testAVD --abi google_apis/x86_64 --package 'system-images;android-29;google_apis;x86_64'
        ls -l $ANDROID_SDK_ROOT/emulator/emulator
        $ANDROID_SDK_ROOT/emulator/emulator -avd testAVD -no-window -no-audio -no-boot-anim &
        sleep 60
        $ANDROID_SDK_ROOT/platform-tools/adb shell input keyevent 82 
   
  
    - name: Run APK
      run: |
        ls -l 
        $ANDROID_SDK_ROOT/platform-tools/adb install -r mobile-automation-maven/tree/master/QrRM.apk
        $ANDROID_SDK_ROOT/platform-tools/adb shell am start -n quocviet.com.vn.qrrm/quocviet.com.vn.qrrm.LoginActivity

    - name: Set up Maven
      run: mvn clean install
