# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        api-level: [21]  # Add the Android API levels you want to test
        target: [default_tuan]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: 8512546  # Thay đổi tùy theo phiên bản Android SDK bạn muốn sử dụng

    - name: Install Android Emulator
      run: sdkmanager "emulator" --sdk_root=${{ env.ANDROID_HOME }} 
    - name: Install necessary components
      run: sdkmanager "platforms;android-21" "system-images;android-21;default;x86" "build-tools;21.1.2" "platform-tools"
    - name: Create AVD
      run: avdmanager create avd -n ${{ matrix.target }} -k "system-images;android-21;default;x86" 
    - name: Start Emulator
      run: $ANDROID_HOME/emulator/emulator -avd ${{ matrix.target }} -no-window
    - name: Build and run APK with Maven
      run:  adb install -r mobile-automation-maven/tree/master/QrRM.apk # Thay thế lệnh này nếu bạn có lệnh khác để xây dựng ứng dụng của mình
    - name: Run your APK
      run: adb shell am start -n quocviet.com.vn.qrrm/quocviet.com.vn.qrrm.LoginActivity  # Thay đổi thành tên package và activity của ứng dụng của bạn
   
    - name: Build with Maven
      run: mvn -B package --file pom.xml

   

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
